version: "3.2"

services:
  api:
    build: ./api
    container_name: challange-lawn-starter-api
    env_file: api/.env
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/vendor
    networks:
      - development_network
    depends_on:
      - db

  app:
    build: ./app
    container_name: challange-lawn-starter-app
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - development_network
    depends_on:
      - api

  db:
    image: postgres:13.1-alpine
    container_name: challange-lawn-starter-db
    restart: always
    env_file: api/.env
    ports:
      - 5432:5432
    networks:
      - development_network

networks:
  development_network:
    driver: bridge
